# demo_rebuild.xdc + UART pins (from eco_rgmii_phy1.xdc)
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN H26 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property PACKAGE_PIN G22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN A23 [get_ports {led[0]}]
set_property PACKAGE_PIN A24 [get_ports {led[1]}]
set_property PACKAGE_PIN D23 [get_ports {led[2]}]
set_property PACKAGE_PIN C24 [get_ports {led[3]}]
set_property PACKAGE_PIN C26 [get_ports {led[4]}]
set_property PACKAGE_PIN D24 [get_ports {led[5]}]
set_property PACKAGE_PIN D25 [get_ports {led[6]}]
set_property PACKAGE_PIN E25 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property SLEW FAST [get_ports {led[*]}]

set_property PACKAGE_PIN Y3  [get_ports rgmii_txctl1]
set_property PACKAGE_PIN AB1 [get_ports rgmii_txc1]
set_property PACKAGE_PIN AF3 [get_ports rgmii_rxctl1]
set_property PACKAGE_PIN AB2 [get_ports rgmii_rxc1]
set_property PACKAGE_PIN AE2 [get_ports {rgmii_rxd1[0]}]
set_property PACKAGE_PIN AE1 [get_ports {rgmii_rxd1[1]}]
set_property PACKAGE_PIN AC1 [get_ports {rgmii_rxd1[2]}]
set_property PACKAGE_PIN AC2 [get_ports {rgmii_rxd1[3]}]
set_property PACKAGE_PIN AB4 [get_ports {rgmii_txd1[0]}]
set_property PACKAGE_PIN AA4 [get_ports {rgmii_txd1[1]}]
set_property PACKAGE_PIN AA3 [get_ports {rgmii_txd1[2]}]
set_property PACKAGE_PIN AA2 [get_ports {rgmii_txd1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxc1]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd1[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rxctl1]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txc1]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd1[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_txctl1]
set_property SLEW FAST [get_ports {rgmii_txd1[*]}]
set_property SLEW FAST [get_ports rgmii_txc1]
set_property SLEW FAST [get_ports rgmii_txctl1]

# UART (CH340E — same pins as the wrapper builds)
set_property PACKAGE_PIN B17 [get_ports rs232_rx]
set_property PACKAGE_PIN A17 [get_ports rs232_tx]
set_property IOSTANDARD LVCMOS33 [get_ports rs232_rx]
set_property IOSTANDARD LVCMOS33 [get_ports rs232_tx]
set_property PULLUP true [get_ports rs232_rx]
set_property DRIVE 12 [get_ports rs232_tx]
set_property SLEW SLOW [get_ports rs232_tx]
